server:
  port: 8082
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:h2:./.local-db/statistics
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      path: /db
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        "[spring.json.use.type.headers]": false
        "[spring.json.value.default.type]": de.sample.schulung.statistics.kafka.CustomerEventRecord
        "[spring.deserializer.value.delegate.class]": de.sample.schulung.statistics.kafka.CustomJsonDeserializer
        "[spring.deserializer.value.function]": de.sample.schulung.statistics.kafka.CustomDeserializationFailureHandler
      group-id: customer-statistics
      auto-offset-reset: earliest
      enable-auto-commit: false
application:
  kafka:
    customer-events:
      topic: ${CUSTOMER_EVENTS_TOPIC_NAME:customer-events}
