server:
  port: 8081
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:h2:./.local-db/data
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      path: /db
      enabled: true
  kafka:
    admin:
      auto-create: ${KAFKA_AUTO_CREATE_TOPICS:true}
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value-serializer: de.sample.schulung.accounts.kafka.CustomJsonSerializer
application:
  kafka:
    customer-events:
      topic: ${CUSTOMER_EVENTS_TOPIC_NAME:customer-events}
      partitions: 5
