GET {{endpoint}}/customers
Accept: application/json

> {%

  client.test('returns valid response', () => {
    client.assert(response.status === 200, 'status code is 200');
    client.assert(response.headers.valueOf('Content-Type') === 'application/json', 'content type is JSON');
    client.assert(Array.isArray(response.body), 'body is an array');
  });
%}

###

GET {{endpoint}}/customers
Accept: text/html

> {%

  client.test('returns valid response', () => {
    client.assert(response.status === 406, 'status code is 406');
  });
%}

###

GET {{endpoint}}/customers?state=active
Accept: application/json

> {%

  client.test('returns valid response', () => {
    client.assert(response.status === 200, 'status code is 200');
    client.assert(response.headers.valueOf('Content-Type') === 'application/json', 'content type is JSON');
    client.assert(Array.isArray(response.body), 'body is an array');
  });
%}

###

GET {{endpoint}}/customers/870a188d-d7dd-4051-bdbe-52f90941d507
Accept: application/json