POST {{endpoint}}/customers
Content-Type: application/json
Accept: application/json

{
  "name": "Tom Mayer",
  "birthdate": "1985-07-30",
  "state": "active"
}

> {%

  client.test('returns valid response', () => {
    client.assert(response.status === 201, 'status code is 201');
    client.assert(response.headers.valueOf('Content-Type') === 'application/json', 'content type is JSON');
    client.assert(response.body['uuid'] !== undefined, 'body contains a uuid');
    client.assert(response.headers.valueOf("Location") !== undefined, 'location header is specified');
  });

  client.global.set('newCustomerUrl', response.headers.valueOf("Location"));

%}

###

GET {{newCustomerUrl}}
Accept: application/json

> {%

  client.test('customer exists', () => {
    client.assert(response.status === 200, 'status code is 200');
  });

%}
